using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BepInEx;
using BepInEx.Logging;

namespace OPERATOR.Debug
{
    // F3: enumerate the game's FULL attachment catalog (LoadoutManager.WeaponModInfo[]) and write a
    // ready-to-paste C# skeleton — a Dictionary<Name, Mod> with zeroed Recoil/Ergo/Weight — to seed
    // the FunctionalWeaponMods per-attachment modifier table. Keyed by the individual attachment Name
    // (not just AttachmentType), so items within a type (e.g. a small vs. large foregrip) can carry
    // different values. The game leaves these fields at 0, so they're emitted blank for you to author.
    internal static class AttachmentDump
    {
        public static void DumpCatalog(ManualLogSource log)
        {
            log.LogInfo("==== [F3] ATTACHMENT CATALOG DUMP ====");

            var lm = LoadoutManager.singleton;
            if (lm == null) { log.LogWarning("  LoadoutManager.singleton is null (load into a match/menu first); aborting."); return; }
            var infos = lm.WeaponModInfo;
            if (infos == null) { log.LogWarning("  LoadoutManager.WeaponModInfo is null; aborting."); return; }

            // Group by AttachmentType, preserving first-seen order.
            var order = new List<WeaponMod.AttachmentType>();
            var byType = new Dictionary<WeaponMod.AttachmentType, List<WeaponModInfo>>();
            int count = infos.Length;
            for (int i = 0; i < count; i++)
            {
                var info = infos[i];
                if (info == null) continue;
                var t = info.AttachmentType;
                if (!byType.TryGetValue(t, out var list)) { list = new List<WeaponModInfo>(); byType[t] = list; order.Add(t); }
                list.Add(info);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by OPERATOR.Debug (F3 — AttachmentDump). One entry per attachment Name.");
            sb.AppendLine("// Fill in Recoil / Ergo / Weight; values may differ per item within an AttachmentType.");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("public static class AttachmentModifiers");
            sb.AppendLine("{");
            sb.AppendLine("    public struct Mod { public float Recoil, Ergo, Weight; public Mod(float r, float e, float w) { Recoil = r; Ergo = e; Weight = w; } }");
            sb.AppendLine();
            sb.AppendLine("    public static readonly Dictionary<string, Mod> Table = new Dictionary<string, Mod>");
            sb.AppendLine("    {");

            var seen = new HashSet<string>();   // keep dictionary keys unique so the skeleton compiles & loads
            int live = 0, dup = 0, noName = 0;
            foreach (var t in order)
            {
                var list = byType[t];
                sb.AppendLine("        // ── " + t + " (" + list.Count + ") ──");
                for (int i = 0; i < list.Count; i++)
                {
                    var info = list[i];
                    string name = Safe(info.Name);
                    string disp = Safe(info.DisplayName);
                    string compat = SafeCompat(info);
                    string suffix = "   // " + (disp.Length > 0 ? disp : "(no display name)") + (compat.Length > 0 ? "  [" + compat + "]" : "");

                    if (name.Length == 0) { sb.AppendLine("        // (no Name)" + suffix); noName++; }
                    else if (!seen.Add(name)) { sb.AppendLine("        // DUPLICATE " + Quote(name) + suffix); dup++; }
                    else { sb.AppendLine("        [" + Quote(name) + "] = new Mod(0f, 0f, 0f)," + suffix); live++; }
                }
                sb.AppendLine();
                log.LogInfo("  " + t + ": " + list.Count);
            }

            sb.AppendLine("    };");
            sb.AppendLine("}");

            string path = Path.Combine(Paths.BepInExRootPath, "AttachmentModifiers.generated.cs");
            try
            {
                File.WriteAllText(path, sb.ToString());
                log.LogInfo($"  {live} attachments ({dup} dup, {noName} unnamed) across {order.Count} types -> {path}");
            }
            catch (Exception e)
            {
                log.LogWarning("  file write failed (" + e.Message + "); dumping inline:");
                log.LogInfo(sb.ToString());
            }
        }

        private static string Safe(string s) => string.IsNullOrEmpty(s) ? "" : s;
        private static string SafeCompat(WeaponModInfo info) { try { return Safe(info.GetCompatibilityString()); } catch { return ""; } }
        private static string Quote(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
